name: clear_notification_tray
description: A plugin to clear notification tray in flutter.
version: 0.0.1
homepage: https://github.com/NischalJoshi777/clear_notification_tray
issue_tracker: https://github.com/NischalJoshi777/clear_notification_tray/issues
platforms:
  android:
  ios:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.clear_notification_tray.clear_notification_tray
        pluginClass: ClearNotificationTrayPlugin
      ios:
        pluginClass: ClearNotificationTrayPlugin