name: clear_notification_tray
description: A plugin to clear notification tray in both android and iOS and reset the iOS badge count.
version: 0.0.3
homepage: https://github.com/NischalJoshi777/clear_notification_tray
issue_tracker: https://github.com/NischalJoshi777/clear_notification_tray/issues
platforms:
  android:
  ios:


environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.clear_notification_tray.clear_notification_tray
        pluginClass: ClearNotificationTrayPlugin
      ios:
        pluginClass: ClearNotificationTrayPlugin